export const { toString, toDateString, toTimeString, toLocaleString, toLocaleDateString, toLocaleTimeString, valueOf, getTime, getFullYear, getUTCFullYear, getMonth, getUTCMonth, getDate, getUTCDate, getDay, getUTCDay, getHours, getUTCHours, getMinutes, getUTCMinutes, getSeconds, getUTCSeconds, getMilliseconds, getUTCMilliseconds, getTimezoneOffset, toUTCString, toISOString, toJSON } = new Date();
console.log('toString', new Date().toString());
console.log('toDateString', new Date().toDateString());
console.log('toTimeString', new Date().toTimeString());
console.log('toLocaleString', new Date().toLocaleString());
console.log('toLocaleDateString', new Date().toLocaleDateString());
console.log('toLocaleTimeString', new Date().toLocaleTimeString());
console.log('valueOf', new Date().valueOf());
console.log('getTime', new Date().getTime());
console.log('getFullYear', new Date().getFullYear());
console.log('getUTCFullYear', new Date().getUTCFullYear());
console.log('getMonth', new Date().getMonth());
console.log('getUTCMonth', new Date().getUTCMonth());
console.log('getDate', new Date().getDate());
console.log('getUTCDate', new Date().getUTCDate());
console.log('getDay', new Date().getDay());
console.log('getUTCDay', new Date().getUTCDay());
console.log('getHours', new Date().getHours());
console.log('getUTCHours', new Date().getUTCHours());
console.log('getMinutes', new Date().getMinutes());
console.log('getUTCMinutes', new Date().getUTCMinutes());
console.log('getSeconds', new Date().getSeconds());
console.log('getUTCSeconds', new Date().getUTCSeconds());
console.log('getMilliseconds', new Date().getMilliseconds());
console.log('getUTCMilliseconds', new Date().getUTCMilliseconds());
console.log('getTimezoneOffset', new Date().getTimezoneOffset());
console.log('toUTCString', new Date().toUTCString());
console.log('toISOString', new Date().toISOString());
console.log('toJSON', new Date().toJSON());

console.log('new Date()', new Date());
console.log('Date()', Date());
console.log('Date.now', Date.now());

console.log('Date.now', Date.now().toExponential());
console.log('Date.now', Date.now().toFixed());
console.log('Date.now', Date.now().toLocaleString());
console.log('Date.now', Date.now().toPrecision());
console.log('Date.now', Date.now().toString());
console.log('Date.now', Date.now().valueOf());